### ISSUE TITLE
Website plan

### ISSUE THREAD

**Issue by bshyong** [Easetravel/hotelwebsite#1]
@dyr429 @xjingg what are your roles and background/experience?

**Comment by xjingg** [comment]
Hello Ben, nice to meet u~ I do the front-end work and Mobile App Development. I am a second-year graduate student in Worcester Polytechnic Institute, major in game development.

**Comment by dyr429** [comment]
Hi Ben, welcome, glad you joined us. I am a first-year graduate student in Northeastern University, major in Computer Science, a full-stack developer. I familiar with Java, C++, Javascript most and also know swift and python.

**Comment by bshyong** [comment]
Awesome. What are you all thinking for the tech stack? I have experience with Rails and React/Redux for front-end. Highly recommend using ReactJS/Redux for the front-end; but back-end you two should find something that you are familiar with and want to work on

**Comment by bshyong** [comment]
I do not have time to write a lot of code but can help you review and provide advice/guidance

**Comment by dyr429** [comment]
That will be great. We currently use NodeJS + ExpressJS + MongoDB for back-end and Angular for front-end. We will focus on website after launch check-in app next week. I will take a look at ReactJS, we can discuss which one to use for front-end soon.

**Comment by bshyong** [comment]
Have you considered https://v4-alpha.getbootstrap.com/ for the CSS/grids? I recommend that you switch to it if possible because it could help with a lot of the responsive styling issues

**Comment by xjingg** [comment]
Thanks for the suggestion, actually we have been using Bootstrap, if you
have time to take a look at the code. We are fixing the styling issues,
mostly because the design data we receive is a fixed value, instead of
relative value. Again, appreciate your help. Feel free to contact us if you
have any suggestion in mind.

**Comment by bshyong** [comment]
Right I also saw the use of Zerogrid in the website, is there a reason for using that too? 

Try to always use EM and REM instead of PX. You can use this conversion tool to help http://pxtoem.com/

**Comment by xjingg** [comment]
There was a section I planned to use Zerogrid, and already replaced that. I leave the Zerogrid there just for backup, and I will clean up the code when I finish Stage1 recently. Thanks for clarifying!
